import React, { useState } from 'react';
import { Download, FileText, Check, Copy, Share2, Sparkles } from 'lucide-react';

interface ExportModalProps {
  paperTitle: string;
  coreConcept: any;
  flowchart: any;
  studentOpportunities: any[];
  tokens: any;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  paperTitle,
  coreConcept,
  flowchart,
  studentOpportunities,
  tokens,
  onClose,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  // Generate clean markdown report
  const generateMarkdown = () => {
    let md = `# Research Analysis & Architecture Report: ${paperTitle}\n\n`;
    md += `*Generated by Computer Science Research Agent (PaperArch)*\n`;
    md += `*Token Budget Audit: ${tokens?.totalTokens || 'N/A'} tokens utilized out of 25,000 maximum constraint*\n\n`;

    md += `## 1. CORE CONCEPT EXTRACTION (<300 words)\n\n`;
    md += `### Problem Statement\n${coreConcept.problemStatement}\n\n`;
    md += `### Primary Methodology\n${coreConcept.primaryMethodology}\n\n`;
    md += `### Key Mathematical & Algorithmic Breakthroughs\n${coreConcept.keyBreakthroughs}\n\n`;
    md += `### Plain-Language Summary\n${coreConcept.summaryPlainLanguage}\n\n`;

    md += `## 2. ARCHITECTURAL FLOWCHART\n\n`;
    md += `\`\`\`mermaid\n[FLOWCHART]\n${flowchart.mermaidCode.trim()}\n\`\`\`\n\n`;
    md += `*Flow Explanation:* ${flowchart.explanation}\n\n`;

    md += `## 3. FUTURE WORK & INTERNSHIP RESUME OPPORTUNITIES (3rd-Year CS Student)\n\n`;
    studentOpportunities.forEach((opp, i) => {
      md += `### Project ${i + 1}: ${opp.projectTitle}\n`;
      md += `- **Exact Extension:** ${opp.exactExtension}\n`;
      md += `- **Targeted Performance Metric:** ${opp.targetedPerformanceMetric}\n`;
      md += `- **Recommended Tech Stack:** ${opp.recommendedTechStack.join(', ')}\n`;
      md += `- **Feasibility & Timeline:** ~${opp.estimatedWeeks || 3} weeks (${opp.difficulty})\n`;
      md += `- **Resume Bullet Point:**\n  > "${opp.resumeBullet}"\n\n`;
      if (opp.implementationMilestones && opp.implementationMilestones.length > 0) {
        md += `**Milestones:**\n`;
        opp.implementationMilestones.forEach((m: string, mIdx: number) => {
          md += `  ${mIdx + 1}. ${m}\n`;
        });
        md += `\n`;
      }
    });

    return md;
  };

  const markdownText = generateMarkdown();

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    const blob = new Blob([markdownText], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${paperTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_research_agent_report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-blue-950 text-blue-400 border border-blue-800">
              <FileText className="w-4 h-4" />
            </span>
            <h3 className="text-sm font-semibold text-slate-100">
              Export Research Architecture & Student Brief
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          <p className="text-xs text-slate-300">
            Export the complete synthesized paper breakdown including the &lt;300-word plain language extraction, Mermaid.js architectural graph TD, and the 3 student development resume projects.
          </p>

          <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-mono text-slate-300 overflow-x-auto max-h-[350px] leading-relaxed select-all">
            {markdownText}
          </pre>
        </div>

        <div className="px-6 py-4 border-t border-slate-800 bg-slate-950 flex flex-wrap items-center justify-between gap-3">
          <span className="text-xs font-mono text-slate-500">
            Formatted in GitHub-flavored Markdown
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-4 py-2 text-xs font-medium rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
            </button>
            <button
              onClick={handleDownloadFile}
              className="flex items-center gap-1.5 px-4 py-2 text-xs font-medium rounded-lg bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white shadow transition-all"
            >
              <Download className="w-4 h-4" />
              <span>Download .MD File</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
